stages: [lint, test]

default:
  image: python:3.12-slim
  before_script:
    - python -V
    - pip install --upgrade pip
    - pip install -r requirements-dev.txt
    # Runtime-Reqs für API-Tests:
    - pip install fastapi "uvicorn[standard]" pydantic

lint:
  stage: lint
  script:
    - pip install ruff
    - ruff check backend

test:
  stage: test
  script:
    - pytest
  artifacts:
    when: always
    reports:
      junit: junit.xml
