image: python:3.12-slim

stages:
  - lint
  - test

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_CACHE_DIR: "0"

cache:
  key: pip-v1
  paths:
    - .pytest_cache/
    - ~/.cache/pip/

.default_install: &default_install
  before_script:
    - python -V
    - pip install --upgrade pip
    - pip install -r requirements-test.txt

lint:
  stage: lint
  <<: *default_install
  script:
    - ruff check .
    # - black --check .
    # optional:
    # - mypy .

pytest:
  stage: test
  <<: *default_install
  script:
    - pytest -q -m "quarantine"
