stages:
  - test

pytest:
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install --upgrade pip
    - pip install pytest
  script:
    # nur stabile Tests laufen lassen
    - pytest -q -m "not quarantine"

quarantine:
  stage: test
  image: python:3.12-slim
  allow_failure: true   # <- Quarantäne darf fehlschlagen
  before_script:
    - pip install --upgrade pip
    - pip install pytest
    - pip install -r requirements.txt

  script:
    - pytest -q -m "quarantine"
