stages: [test]

pytest:
  stage: test
  image: python:3.12.3
  before_script:
    - python -V
    - pip install --upgrade pip
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - pip install pytest
  script:
    - pytest -q
