stages:
  - test

pytest:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install pytest
  script:
    - pytest -q
    - echo "CI_REGISTRY=$CI_REGISTRY"
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
