# compose.prod.yml  (ohne "version:")
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: anonymizer-backend:latest
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - backend_data:/app   # optional: persist mapping.txt

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: anonymizer-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  backend_data: {}
