# ruff.toml
line-length = 100
target-version = "py312"

[lint]
select = [
  "E","F",        # pycodestyle + pyflakes
  "I",            # isort
  "UP",           # pyupgrade
  "B",            # bugbear
]

extend-select = ["I"]            # isort-Regeln aktivieren

ignore = [
  "E501",         # Zeilenlänge, wir managen über line-length
]

[lint.isort]
known-first-party = ["api_server", "anonymizer", "anonymizer_core", "backend"]

[format]
line-ending = "lf"
quote-style = "double"



