# ruff.toml

[lint]
# Nur Kernchecks: E (pycodestyle) & F (pyflakes)
select = ["E", "F"]
# Wenn du isort sp채ter wieder willst, f체ge "I" zur체ck hinzu.
# extend-select = ["I"]

# Tests von Import-Sortierung explizit ausnehmen
per-file-ignores = { "backend/tests/**" = ["I001", "I002"] }

[lint.isort]
# Falls du "I" sp채ter wieder aktivierst, kennt Ruff eure Module:
known-first-party = ["api_server", "anonymizer", "anonymizer_core", "backend"]

[format]
line-ending = "lf"
