image:
  registry: gitlab.local:5050/<group>/<project>
  pullSecrets:
    - name: gitlab-regcred

backend:
  repository: anonymizer-backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  port: 8000

frontend:
  repository: anonymizer-frontend
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  port: 8080

ingress:
  enabled: false
