global:
  imageRegistry: ""               # keine Doppel-Prefixes!

image:
  repositoryFrontend: anonymizer-frontend
  tagFrontend: local
  repositoryBackend: anonymizer-backend
  tagBackend: local
  pullPolicy: Never

#image:
#  repositoryFrontend: ghcr.io/<owner>/<repo>/anonymizer-frontend
#  tagFrontend: v0.1.0
#  repositoryBackend: ghcr.io/<owner>/<repo>/anonymizer-backend
#  tagBackend: v0.1.0
#  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  hosts:
    frontend: anonymizer.local
    backend: api.anonymizer.local

backend:
  repository: k3d-registry:5000/anonymizer-backend
  tag: "dev"
  pullPolicy: IfNotPresent
  replicas: 1
  port: 8000

frontend:
  repository: k3d-registry:5000/anonymizer-frontend
  tag: "dev"
  pullPolicy: IfNotPresent
  replicas: 1
  port: 80
