image:
  registry: gitlab.local:5050/<group>/<project>
  pullSecrets:
    - name: gitlab-regcred

backend:
  repository: anonymizer-backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  replicas: 1
  port: 8000            # Container-Port (wie bisher genutzt)
  servicePort: 80       # Externer Service-Port (separat steuerbar)
  resources:
    requests: { cpu: "50m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }

frontend:
  repository: anonymizer-frontend
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  replicas: 1
  # Container-Port (nginx-unprivileged nutzt standardmäßig 8080; dein Image evtl. 80)
  containerPort: 8080
  # Service-Port bleibt 80 für „normales“ Routing
  servicePort: 80

  resources:
    requests: { cpu: "50m", memory: "64Mi" }
    limits:   { cpu: "300m", memory: "256Mi" }

ingress:
  enabled: false
  className: ""
  host: anonymizer.local




