apiVersion: v1
kind: Service
metadata:
  name: {{ include "anonymizer.fullname" . }}-backend
  labels: {{- include "anonymizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: { app: {{ include "anonymizer.fullname" . }}, tier: backend }
  ports:
    - name: http
      port: {{ .Values.backend.servicePort | default ( .Values.backend.port | default 8000 ) }}  # Service-Port
      targetPort: http            # <— benannter Container-Port aus Deployment
      protocol: TCP
      appProtocol: http           # optional, aber hilfreich für Ingress/Gateways
