name: build
on: [push, pull_request]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build FE+BE (registry-free)
        run: make build    # REGISTRY_HOST unset -> :local images, always green
