name: build
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build (no registry, no login)
        run: make build

      - name: Smoke backend
        run: docker run --rm anonymizer-backend:local python -c "print('smoke ok')"

      - name: Smoke frontend
        run: |
          cid=$(docker run -d -p 8080:80 anonymizer-frontend:local)
          sleep 2
          docker logs "$cid" || true
          docker rm -f "$cid"
