name: Package Helm chart (no push)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
      - '.github/workflows/helm-chart.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Lint chart
        run: helm lint charts/anonymizer

      - name: Package chart
        run: helm package charts/anonymizer --destination dist

      # Optional: Artefakt anhängen (praktisch für Download/Review)
      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: anonymizer-chart-${{ github.sha }}
          path: dist/*.tgz
